baseurl = "https://note.jaymi.cn/"
languageCode = "en-us"
title = "Jaymi's note"
theme = "Maupassant"

[author]
  name = "Jaymi"

[params]
  author = "Jaymi"
  subtitle = "专注于Python、Golang、互联网"
  keywords = "博客,项目管理,python"
  description = "专注于Python、Golang、互联网"

[params.utteranc]
    enable = true
    repo = "aubucuo/my-hugo-by-netlify"    #存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4