baseurl = "http://note.jaymi.cn/"
languageCode = "en-us"
title = "Jaymi's note"
theme = "Maupassant"

[params.utteranc]
    enable = true
    repo = "aubucuo/my-hugo-by-netlify"    #存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种